myrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  FLsuspension_position_controller:
    type: effort_controllers/JointPositionController
    joint: suspension_joint1
    pid: {p: 10000.0, i: 0.0, d: 1000}
    
  FRsuspension_position_controller:
    type: effort_controllers/JointPositionController
    joint: suspension_joint2
    pid: {p: 10000.0, i: 0.0, d: 1000}
    
  BLsuspension_position_controller:
    type: effort_controllers/JointPositionController
    joint: suspension_joint3
    pid: {p: 10000.0, i: 0.0, d: 1000}
    
  BRsuspension_position_controller:
    type: effort_controllers/JointPositionController
    joint: suspension_joint4
    pid: {p: 10000.0, i: 0.0, d: 1000}
    
  FLwheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint1
    pid: {p: 100, i: 0.00, d: 0}
    
  FRwheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint2
    pid: {p: 100, i: 0.00, d: 0}
    
  BLwheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint3
    pid: {p: 100, i: 0.00, d: 0}
    
  BRwheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint4
    pid: {p: 100, i: 0.00, d: 0}

